fixed the shell identifying logic - it was inverted

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -15,11 +15,14 @@ usage ()
     echo "       --skip - skip one or more validations:"
     echo "                perlcompile"
     echo "                perltidy"
+    echo "                shellcheck"
     echo "       When actually run as a hook, set GIT_PRE_COMMIT_HOOK_ARGS to a single"
     echo "       string with the options you want to use before committing:"
     echo
     echo "       GIT_PRE_COMMIT_HOOK_ARGS='--verbose --skip perltidy' git commit ..."
     echo
+    echo "       You can also run it in 'test' mode by direct invocation in the .git"
+    echo "       directory."
 }
 
 ## Don't do my checks if Perl testing involves git commands.
@@ -36,40 +39,39 @@ pre_commit_error_echo ()
     echo 'ERROR>>>' pre-commit hook: "$@"
 }
 
-## See if we are in a real commit or not
-typeset dry_run=0
-if [ -z "$GIT_AUTHOR_DATE" ]
-then
-    dry_run=1
-    pre_commit_ok_echo "Dry run mode - no commit in progress."
-fi
-
 ##
 ## args and opts
 ##
-typeset -A skips
-typeset opt_verbose=1
-typeset opt_a=0
-typeset OPTSARGS=$(getopt -o ats:vh --long tags,skip:,verbose,help -n 'pre-commit' -- $GIT_PRE_COMMIT_HOOK_ARGS "$@")
-eval set -- "$OPTSARGS"
-while true
+declare -A skips
+declare opt_verbose=1
+declare opt_a=0
+declare moreopts
+moreopts=1
+while [[ "$1" =~ ^- ]] && ((moreopts))
 do
-    case "$1" in
-        -a)
-            shift
+    ## Strip all leading dashes here so that -foo and --foo can both
+    ## be processed as 'foo'.
+    declare original="$1"
+    declare option
+    option=$(dashstripper "$original")
+    shift ## That way you avoid endless loops on invalid options.
+
+    case $option in
+        a)
             opt_a=1 ;;
-        -t|--tags)
-            shift
-            grep '##tags' ${BASH_SOURCE[0]} | sed 's/##tags//' | grep -v grep
+        t|tags)
+            grep '##tags' "${BASH_SOURCE[0]}" | sed 's/##tags//' | grep -v grep
             exit 0 ;;
-        -s|--skip)
-            shift
+        s|skip)
             skips[$1]=1;
             shift ;;
-        -v|--verbose)
-            shift
+        v|verbose)
             opt_verbose=1 ;;
-        -h|--help)
+        x)
+            set -x
+            trap "set +x" EXIT
+            ;;
+        h|help)
             usage
             exit 0 ;;
         --) shift; break ;; ## end of opts, remaining $*, if any, are args
@@ -83,13 +85,14 @@ done
 
 ## We use a temp file to process output instead of $() capturing so we don't
 ## lose the newlines...
-typeset tfile=$(mktemp)
+declare tfile
+tfile=$(mktemp)
 
 ## ...and we set up a trap for cleanup
 trap finish EXIT SIGINT
 
 ## Assume correctness
-typeset exitval=0
+declare exitval=0
 
 ##
 ## Functions
@@ -97,9 +100,9 @@ typeset exitval=0
 
 finish ()
 {
-    if [ -e $tfile ]
+    if [ -e "$tfile" ]
     then
-        rm -rf $tfile
+        rm -rf "$tfile"
     fi
 }
 
@@ -107,13 +110,14 @@ check ()
 {
     local tfile=$1
     shift
-    local tcount=$(wc -l $tfile | sed 's/ .*//')
-    if [ $tcount != 0 ]
+    local tcount
+    tcount=$(wc -l "$tfile" | sed 's/ .*//')
+    if [ "$tcount" != 0 ]
     then
         ## This is the error message
         echo
         pre_commit_error_echo "$1"
-        cat $tfile
+        cat "$tfile"
         exitval=1
         return 1
     else
@@ -128,65 +132,95 @@ check ()
 ##
 
 ## Get the top level dir of the repo
-typeset tl=$(git rev-parse --show-toplevel)
-typeset files
+declare -a files
 if ((opt_a))
 then
     ## Like git's -a, process modified files even if not 'git add'ed
-    files=$(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^[ACM] / or m/^.[ACM]/')
+    readarray -t files < <(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^[ACM] / or m/^.[ACM]/')
 else
-    files=$(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^[ACM] /')
+    readarray -t files < <(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^[ACM] /')
 fi
-typeset delfiles=$(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^D /')
-typeset huhfiles=$(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^\? /')
+declare -a delfiles
+readarray -t delfiles < <(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^D /')
+declare -a huhfiles
+readarray -t huhfiles < <(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^\? /')
 
 if ((opt_verbose))
 then
-    typeset tmpf=$(mktemp)
-    git status --porcelain 1>$tmpf 2>&1
-    if [ -s $tmpf ]
+    declare tmpf
+    tmpf=$(mktemp)
+    git status --porcelain 1>"$tmpf" 2>&1
+    if [ -s "$tmpf" ]
     then
         pre_commit_ok_echo Current status:
-        cat $tmpf
+        cat "$tmpf"
     fi
-    \rm -f $tmpf
+    \rm -f "$tmpf"
 
-    typeset fcount=$(echo $files | wc -w)
-    typeset text='files to process'
+    declare fcount
+    fcount=${#files[@]}
+    declare text='files to process'
     ((fcount == 1 )) && text='file to process'
-    pre_commit_ok_echo $fcount $text
+    pre_commit_ok_echo "$fcount" "$text"
 
-    fcount=$(echo $delfiles | wc -w)
+    fcount=${#delfiles[@]}
     text='files to be skipped because they are being deleted'
     if ((fcount))
     then
         ((fcount == 1 )) && text='file to be skipped because it is being deleted'
-        echo pre-commit  hook: $fcount $text
+        echo pre-commit  hook: "$fcount" "$text"
     fi
 
-    fcount=$(echo $huhfiles | wc -w)
+    fcount=${#huhfiles[@]}
     text='files to be skipped because they are not being tracked'
     if ((fcount))
     then
         ((fcount == 1 )) && text='file to be skipped because it is not being tracked'
-        echo pre-commit  hook: $fcount $text
+        echo pre-commit  hook: "$fcount" "$text"
     fi
 fi
 
 ## Isolate groups of files here. So far, only checking for Perl.
-typeset perlfiles
-typeset file
-for file in $files
+declare perlfiles
+declare shellfiles
+declare do_shellcheck=0
+declare file
+shellcheck -V 1>/dev/null 2>&1 && do_shellcheck=1
+
+for file in "${files[@]}"
 do
-    head -1 $file | grep perl | grep -E '^#!' > /dev/null
-    if [ "$?" == '0' ]
+    declare assigned=0
+
+    if ((!assigned))
     then
-        perlfiles="$perlfiles $file"
-    else
-        echo $file | grep -iE '\.(p[ml]|t|sgi)$' > /dev/null
-        if [ "$?" == '0' ]
+        if head -1 "$file" | grep perl | grep -E '^#!' > /dev/null
         then
-            perlfiles="$perlfiles $file"
+            [ -n "$perlfiles" ] \
+                && perlfiles="$perlfiles $file" \
+                && perlfiles="$file"
+            assigned=1
+        fi
+    fi
+
+    if ((!assigned))
+    then
+        if echo "$file" | grep -iE '\.(p[ml]|t|sgi)$' > /dev/null
+        then
+            [ -n "$perlfiles" ] \
+                && perlfiles="$perlfiles $file" \
+                && perlfiles="$file"
+            assigned=1
+        fi
+    fi
+
+    if ((!assigned))
+    then
+        if head -1 "$file" | grep -E -- '-\*- sh|env bash|/bash|/sh' 1>/dev/null 2>&1
+        then
+            [ -n "$shellfiles" ] \
+                && shellfiles="$shellfiles $file" \
+                && shellfiles="$file"
+            assigned=1
         fi
     fi
 done
@@ -195,22 +229,22 @@ done
 ## The tests...
 ##
 
-if [ -n "$files" ]
+if ((${#files[@]}))
 then
-    touch $tfile
+    touch "$tfile"
 
     ##
     ## check: files being edited, not saved
     ##
-    for i in $files
+    for i in "${files[@]}"
     do
-        emacsfile="$(dirname $(realpath $i))/.#$(basename $i)"
-        if [ -h $emacsfile ]
+        emacsfile="$(dirname "$(realpath "$i")")/.#$(basename "$i")"
+        if [ -h "$emacsfile" ]
         then
-            echo $i >> $tfile
+            echo "$i" >> "$tfile"
         fi
     done
-    check $tfile \
+    check "$tfile" \
           "Write your emacs buffers for these files:" \
           "No open emacs buffers."
 
@@ -220,35 +254,32 @@ then
 
     ## These two are Perl constructs, but we could use them temporarily in any
     ## file type.
-    grep -H -n -E -i '=for (later|comparison|commentout|review)' $files 1>$tfile 2>&1
-    check $tfile \
+    grep -H -n -E -i '=for (later|comparison|commentout|review)' "${files[@]}" 1>"$tfile" 2>&1
+    check "$tfile" \
           "One or more files contain suspicious Perl commenting. Delete old code, do not just comment it out. Don't add inactive code until you are ready to use it." \
           "No suspicious Perl commenting, old code."
 
-    grep -H -n -E -i '=for (remove|restore)_before_commit' $files 1>$tfile 2>&1
-    check $tfile \
+    grep -H -n -E -i '=for (remove|restore)_before_commit' "${files[@]}" 1>"$tfile" 2>&1
+    check "$tfile" \
           "One or more files contain suspicious Perl commenting. Put back original code; remove your short term test changes." \
           "No suspicious Perl commenting, test code."
 
     if [ -n "$perlfiles" ]
     then
         ##
-        ## These are Perl constructs that only make sense in Perl code.
-        ##
-
-        ##
         ## check: Perl debug statements
         ##
-        grep -H -n -E '\$DB::s(ingle|tep)' $perlfiles 1>$tfile 2>&1
-        check $tfile \
+        # shellcheck disable=2016
+        grep -H -n -E '\$DB::s(ingle|tep)' "$perlfiles" 1>"$tfile" 2>&1
+        check "$tfile" \
               "One or more files has Perl-debugger-related statements. Please remove instrumentation." \
               "No Perl-debugger-related statements."
 
         ##
         ## check: testing utilities left in the code
         ##
-        grep -H -n -E 'TestingUtils' $perlfiles | grep -v TestingUtils.pm  1>$tfile 2>&1
-        check $tfile \
+        grep -H -n -E 'TestingUtils' "$perlfiles" | grep -v TestingUtils.pm  1>"$tfile" 2>&1
+        check "$tfile" \
               "One or more files is using the TestingUtils module. Please remove it." \
               "TestingUtils module not found."
 
@@ -262,23 +293,24 @@ then
         if [ -n "${skips[perlcompile]}" ]
         then
             ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl compile check, by request."
-        elif [ ! -e $gitroot/t/bin/apply-compile-check-everywhere ]
+        elif [ ! -e "$gitroot/t/bin/apply-compile-check-everywhere" ]
         then
             ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl compile check, no test file."
         else
             cartonexec=''
-            if [ -e $gitroot/runtests.local ]
+            if [ -e "$gitroot/runtests.local" ]
             then
                 pre_commit_ok_echo "Sourcing $gitroot/runtests.local for perl compile tests."
-                . /$gitroot/runtests.local
+                # shellcheck disable=SC1090
+                . "/$gitroot/runtests.local"
                 if [ "$RUNTESTS_USE_CARTON" = '1' ]
                 then
                     cartonexec='carton exec'
                 fi
             fi
-            $cartonexec $gitroot/t/bin/apply-compile-check-everywhere $perlfiles 1>$tfile 2>&1
-            check $tfile \
-                  "One or more files has syntax errors. Please check." \
+            $cartonexec "$gitroot/t/bin/apply-compile-check-everywhere" "$perlfiles" 1>"$tfile" 2>&1
+            check "$tfile" \
+                  "One or more files has syntax errors. Please review." \
                   "No Perl compile errors."
         fi
 
@@ -290,22 +322,35 @@ then
         if [ -n "${skips[perltidy]}" ]
         then
             ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl perltidy check, by request."
-        elif [ ! -e $gitroot/t/bin/apply-perltidy-everywhere ]
+        elif [ ! -e "$gitroot/t/bin/apply-perltidy-everywhere" ]
         then
             ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl perltidy check, no test file."
         else
-            $gitroot/t/bin/apply-perltidy-everywhere $perlfiles 1>$tfile 2>&1
-            check $tfile \
-                  "One or more files has formatting errors. Please check." \
+            "$gitroot/t/bin/apply-perltidy-everywhere" "$perlfiles" 1>"$tfile" 2>&1
+            check "$tfile" \
+                  "One or more files has formatting errors. Please review." \
                   "No Perl perltidy errors."
+        fi
+    fi
+
+    if [ -n "$shellfiles" ]
+    then
+        if ((do_shellcheck==1))
+        then
+            shellcheck "$shellfiles" 1>"$tfile" 2>&1
+            check "$tfile" \
+                  "One of more files has failed shellcheck checks. Please review." \
+                  "No shellcheck errors."
+        else
+            echo "Skipping shell checks, 'shellcheck' not found."
         fi
     fi
 
     ##
     ## check; git conflict markers
     ##
-    grep -H -n -E '^<<<<<<<|>>>>>>>$' $files 1>$tfile 2>&1
-    check $tfile \
+    grep -H -n -E '^<<<<<<<|>>>>>>>$' "${files[@]}" 1>"$tfile" 2>&1
+    check "$tfile" \
           "One or more files contains a git conflict marker. Please address." \
           "No git conflict markers."
 
@@ -318,8 +363,8 @@ then
     ## of code that we know we need to clean up before committing. In the
     ## limited number of utilities that manipulate files with GCS, we add the
     ## GCSLITERAL caveat.
-    grep -H -n -E '<(gitcommitstop|GCS)>' $files | grep -v '<GCSLITERAL>' 1>$tfile 2>&1
-    check $tfile \
+    grep -H -n -E '<(gitcommitstop|GCS)>' "${files[@]}" | grep -v '<GCSLITERAL>' 1>"$tfile" 2>&1
+    check "$tfile" \
           "One or more files has an explicit commit stop. Please address." \
           "No explicit commit stops."
 fi
