lots of changes, should have catalogued them

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,7 +1,7 @@
 #!/opt/bb/bin/bash
 
 ##
-## Various checks, pre-commit
+## Various checks, pre-commit, bail early
 ##
 
 ## Don't do my checks if I say not to
@@ -14,104 +14,9 @@ fi
 ## Don't do my checks if Perl testing involves git commands.
 [ "$HARNESS_ACTIVE" = '1' ] && exit 0
 
-pre_commit_ok_echo ()
-{
-    echo pre-commit hook: "$@"
-}
-
-pre_commit_error_echo ()
-{
-    echo 'ERROR>>>' pre-commit hook: "$@"
-}
-
-##
-## args and opts
-##
-declare -A skips
-declare opt_verbose=1
-declare opt_a=0
-declare moreopts
-declare helpnotallowed=0
-declare opt_a_notallowed=0
-moreopts=1
-
-pre_commit_ok_echo "Original args to hook: $*"
-
-if [ -n "$GIT_PRE_COMMIT_HOOK_ARGS" ] \
-       || [ -n "$GPCHA" ]
-then
-    eval set -- "$GIT_PRE_COMMIT_HOOK_ARGS" "$GPCHA"
-    helpnotallowed=1
-    opt_a_notallowed=1
-fi
-
-while [[ "$1" =~ ^- ]] && ((moreopts))
-do
-    ## Strip all leading dashes here so that -foo and --foo can both
-    ## be processed as 'foo'.
-    declare original="$1"
-    declare option
-    option=$(dashstripper "$original")
-    shift ## That way you avoid endless loops on invalid options.
-
-    case $option in
-        a)
-            if((opt_a_notallowed))
-            then
-                pre_commit_ok_echo "--a not allowed in GIT_PRE_COMMIT_HOOK_ARGS. Ignoring."
-            else
-                opt_a=1
-            fi
-            ;;
-        s|skip)
-            if [ "$1" == 'all' ]
-            then
-                echo "SKIP ALL - PRE_COMMIT HOOK EXITS 0"
-                exit 0
-            fi
-            skips[$1]=1;
-            shift ;;
-        q|quiet)
-            opt_verbose=0 ;;
-        x)
-            set -x
-            trap "set +x" EXIT
-            ;;
-        h|help)
-            if((helpnotallowed))
-            then
-                pre_commit_ok_echo "--help not allowed in GIT_PRE_COMMIT_HOOK_ARGS. Ignoring."
-            else
-                pod2text "$0" | ${PAGER:cat}
-                exit 0
-            fi
-            ;;
-        --) shift; break ;; ## end of opts, remaining $*, if any, are args
-        *) echo "Internal error!"; pod2text "$0" | ${PAGER:cat}; exit 1 ;;
-    esac
-done
-
-##
-## inits and globals
-##
-
-## We use a temp file to process output instead of $() capturing so we don't
-## lose the newlines...
-declare tfile
-tfile=$(mktemp)
-
-## ...and we set up a trap for cleanup
-trap finish EXIT SIGINT
-
-## Assume correctness
-declare exitval=0
-
-gitroot=$(git rev-parse --show-toplevel)
-
 ##
 ## Functions
 ##
-
 finish ()
 {
     if [ -e "$tfile" ]
@@ -143,6 +48,94 @@ check ()
     fi
 }
 
+pre_commit_ok_echo ()
+{
+    echo pre-commit hook: "$@"
+}
+
+pre_commit_error_echo ()
+{
+    echo 'ERROR>>>' pre-commit hook: "$@"
+}
+
+##
+## Globals and inits
+##
+
+## We use a temp file to process output instead of $() capturing so we don't
+## lose the newlines...
+declare tfile
+tfile=$(mktemp)
+
+## ...and we set up a trap for cleanup.
+trap finish EXIT SIGINT
+
+declare exitval=0 ## Assume correctness.
+
+declare gitroot
+gitroot=$(git rev-parse --show-toplevel)
+
+##
+## args and opts
+##
+declare -A skips
+declare opt_verbose=1
+declare opt_nocommit=0
+declare moreopts
+declare helpnotallowed=0
+moreopts=1
+
+pre_commit_ok_echo "Original args to hook: $*"
+
+if [ -n "$GIT_PRE_COMMIT_HOOK_ARGS" ] \
+       || [ -n "$GPCHA" ]
+then
+    eval set -- "$GIT_PRE_COMMIT_HOOK_ARGS" "$GPCHA"
+    helpnotallowed=1
+fi
+
+while [[ "$1" =~ ^- ]] && ((moreopts))
+do
+    ## Strip all leading dashes here so that -foo and --foo can both
+    ## be processed as 'foo'.
+    declare original="$1"
+    declare option
+    option=$(dashstripper "$original")
+    shift ## That way you avoid endless loops on invalid options.
+
+    case $option in
+        s|skip)
+            if [ "$1" == 'all' ]
+            then
+                echo "SKIP ALL - PRE_COMMIT HOOK EXITS 0"
+                exit 0
+            fi
+            skips[$1]=1;
+            shift ;;
+        q|quiet)
+            opt_verbose=0 ;;
+        v|verbose)
+            opt_verbose=1 ;;
+        nocommit)
+            opt_nocommit=1 ;;
+        x)
+            set -x
+            trap "set +x" EXIT
+            ;;
+        h|help)
+            if((helpnotallowed))
+            then
+                pre_commit_ok_echo "--help not allowed in GIT_PRE_COMMIT_HOOK_ARGS. Ignoring."
+            else
+                pod2text "$0" | ${PAGER:cat}
+                exit 0
+            fi
+            ;;
+        --) shift; break ;; ## end of opts, remaining $*, if any, are args
+        *) echo "Internal error!"; pod2text "$0" | ${PAGER:cat}; exit 1 ;;
+    esac
+done
+
 ##
 ## Main
 ##
@@ -151,68 +144,54 @@ check ()
 ## Get the list of files being committed
 ##
 declare -a gitobjs
-if ((opt_a))
-then
-    ## Like git's -a, process modified files even if not 'git add'ed
-    readarray -t gitobjs < <(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^[ACM] / or m/^.[ACM]/')
-    pre_commit_ok_echo "We just processed -a inside the hook"
-else
-    readarray -t gitobjs < <(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^[ACM] /')
-fi
+readarray -t gitobjs < <(git diff-index --cached HEAD | perl -ane 'print "$F[-1]=>$F[-2]\n"')
 declare -a files
 declare -a nonfiles
+
+((opt_verbose)) && pre_commit_ok_echo Current status:
 for obj in "${gitobjs[@]}"
 do
-    if [[ -f $obj ]]
+    file=${obj%%=>*}
+    gitstat=${obj##*=>}
+    if [[ $gitstat == 'D' ]]
+    then
+        delgitobjs+=("$file")
+        continue
+    elif [[ -f $obj ]]
     then
         files+=("$obj")
     else
         nonfiles+=("$obj")
     fi
+    ((opt_verbose)) && echo "$obj"
 done
-declare -a delgitobjs
-readarray -t delgitobjs < <(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^D /')
-declare -a huhgitobjs
-readarray -t huhgitobjs < <(git status --porcelain  | perl -ane 'print $F[1],qq(\n) if m/^\? /')
 
 if ((opt_verbose))
 then
-    declare tmpf
-    tmpf=$(mktemp)
-    git status --porcelain 1>"$tmpf" 2>&1
-    if [ -s "$tmpf" ]
-    then
-        pre_commit_ok_echo Current status:
-        cat "$tmpf"
-    fi
-    \rm -f "$tmpf"
-
     declare fcount
     declare text
 
     fcount=${#files[@]}
-    text='files to process'
-    (( fcount == 1 )) && text='file to process'
+    text='file'; (( fcount != 1 )) && text="${text}s"; text="${text} to validate"
     pre_commit_ok_echo "$fcount" "$text"
 
     fcount=${#nonfiles[@]}
-    text='non-files to process'
-    (( fcount == 1 )) && text='non-file to process'
-    (( fcount > 0 )) && pre_commit_ok_echo "$fcount" "$text"
+    if (( fcount > 0 ))
+    then
+        text='non-file'; (( fcount != 1 )) && text="${text}s"; text="${text} to validate"
+        pre_commit_ok_echo "$fcount" "$text"
+    fi
 
     fcount=${#delgitobjs[@]}
-    text='git objects to be skipped because they are being deleted'
-    (( fcount == 1 )) && text='git object to be skipped because it is being deleted'
-    (( fcount > 0 )) && pre_commit_ok_echo "$fcount" "$text"
-
-    fcount=${#huhgitobjs[@]}
-    text='git objects to be skipped because they are not being tracked'
-    (( fcount == 1 )) && text='git object to be skipped because it is not being tracked'
-    (( fcount > 0 )) && pre_commit_ok_echo "$fcount" "$text"
+    if (( fcount > 0 ))
+    then
+        text='git object'; (( fcount != 1 )) && text="${text}s"; text="${text} to be unvalidated because they are being deleted"
+        pre_commit_ok_echo "$fcount" "$text"
+    fi
 fi
 
 ##
-## Do filtering
+## Do filtering.
 ##
 declare -A fileskips
 declare ignore_file="$gitroot/.pre-commit-ignore"
@@ -236,19 +215,28 @@ then
 fi
 
 ##
-## Isolate groups of files here.
+## Isolate specific groups of files.
 ##
 declare -a perlfiles
+declare do_perl=0
 declare -a shellfiles
 declare do_shellcheck=0
 declare -a pythonfiles
 declare do_python=0
 declare file
 
+## Make sure the check programs are installed if we are not skipping that
+## particular check.
+{ [ -z "${skips[perl]}" ] \
+      && [ -z "${skips[perltidy]}" ] \
+      && [ -z "${skips[perlcompile]}" ] ; } \
+    && perl -V 1>/dev/null 2>&1 && do_perl=1
 { [ -z "${skips[shellcheck]}" ] && [ -z "${skips[shell]}" ] ; } \
     && shellcheck -V 1>/dev/null 2>&1 && do_shellcheck=1
 { [ -z "${skips[python]}" ] && [ -z "${skips[py]}" ] ; } \
     && python -V 1>/dev/null 2>&1 && do_python=1
+
+## Now group them.
 for file in "${files[@]}"
 do
     if head -1 "$file" | grep perl | grep -E '^#!' > /dev/null \
@@ -305,87 +293,90 @@ then
 
     if ((${#perlfiles[@]}))
     then
-        ##
-        ## check: Perl debug statements
-        ##
-        # shellcheck disable=2016
-        grep -H -n -E '\$DB::s(ingle|tep)' "${perlfiles[@]}" 1>"$tfile" 2>&1
-        check "$tfile" \
-              "One or more files has Perl-debugger-related statements. Please remove instrumentation."
-
-        ##
-        ## check: testing utilities left in the code
-        ## BB SPECIFIC
-        ##
-        grep -H -n -E 'TestingUtils' "${perlfiles[@]}" | grep -v TestingUtils.pm  1>"$tfile" 2>&1
-        check "$tfile" \
-              "One or more files is using the TestingUtils module. Please remove it."
-
-        ##
-        ## check: repo compile tests
-        ##
-        if [ -n "${skips[perlcompile]}" ] \
-               || [ -n "${skips[perl]}" ]
+        if ((do_perl==1))
         then
-            ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl compile check, by request."
-        else
-            declare runcheck=0
-            if [ -e "$gitroot/t/bin/apply-compile-check-everywhere" ]
+            ##
+            ## check: Perl debug statements
+            ##
+            # shellcheck disable=2016
+            grep -H -n -E '\$DB::s(ingle|tep)' "${perlfiles[@]}" 1>"$tfile" 2>&1
+            check "$tfile" \
+                  "One or more files has Perl-debugger-related statements. Please remove instrumentation."
+
+            ##
+            ## check: testing utilities left in the code
+            ## BB SPECIFIC
+            ##
+            grep -H -n -E 'TestingUtils' "${perlfiles[@]}" | grep -v TestingUtils.pm  1>"$tfile" 2>&1
+            check "$tfile" \
+                  "One or more files is using the TestingUtils module. Please remove it."
+
+            ##
+            ## check: repo compile tests
+            ##
+            if [ -n "${skips[perlcompile]}" ]
             then
-                cartonexec=''
-                if [ -e "$gitroot/runtests.local" ]
+                ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl compile check, by request."
+            else
+                declare runcheck=0
+                if [ -e "$gitroot/t/bin/apply-compile-check-everywhere" ]
                 then
-                    pre_commit_ok_echo "Sourcing $gitroot/runtests.local for perl compile tests."
-                    # shellcheck disable=SC1090
-                    . "/$gitroot/runtests.local"
-                    if [ "$RUNTESTS_USE_CARTON" = '1' ]
+                    cartonexec=''
+                    if [ -e "$gitroot/runtests.local" ]
                     then
-                        cartonexec='carton exec'
+                        pre_commit_ok_echo "Sourcing $gitroot/runtests.local for perl compile tests."
+                        # shellcheck disable=SC1090
+                        . "/$gitroot/runtests.local"
+                        if [ "$RUNTESTS_USE_CARTON" = '1' ]
+                        then
+                            cartonexec='carton exec'
+                        fi
                     fi
-                fi
-                $cartonexec "$gitroot/t/bin/apply-compile-check-everywhere" "${perlfiles[@]}" 1>"$tfile" 2>&1
-                runcheck=1
-            elif [ -e "${TILDAE:-$HOME}/personal/bin/apply-compile-check-everywhere" ]
-            then
-                "${TILDAE:-$HOME}/personal/bin/apply-compile-check-everywhere" "${perlfiles[@]}" 1>"$tfile" 2>&1
-                runcheck=1
-            else
-                ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl compile check, no perl compile check helpers found."
-            fi
-            ((runcheck==1)) && check "$tfile" \
-                                     "One or more files has syntax errors. Please review."
-        fi
-
-        ##
-        ## check: repo tidy tests
-        ##
-        if [ -n "${skips[perltidy]}" ] \
-               || [ -n "${skips[perl]}" ]
-        then
-            ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl perltidy check, by request."
-        else
-            declare remediation
-            declare tidycmd
-            declare runcheck=0
-            for tidycmd in \
-                "$gitroot/t/bin/apply-perltidy-everywhere" \
-                    "${TILDAE:-$HOME}/personal/bin/apply-perltidy-everywhere"
-            do
-                if [ -e "$tidycmd" ]
-                then
-                    "$tidycmd" "${perlfiles[@]}" 1>"$tfile" 2>&1
+                    $cartonexec "$gitroot/t/bin/apply-compile-check-everywhere" "${perlfiles[@]}" 1>"$tfile" 2>&1
                     runcheck=1
-                    remediation="To correct, run $tidycmd --update ${perlfiles[*]}"
-                    break
+                elif [ -e "${TILDAE:-$HOME}/personal/bin/apply-compile-check-everywhere" ]
+                then
+                    "${TILDAE:-$HOME}/personal/bin/apply-compile-check-everywhere" "${perlfiles[@]}" 1>"$tfile" 2>&1
+                    runcheck=1
+                else
+                    ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl compile check, no perl compile check helpers found."
                 fi
-            done
-            if ((runcheck==1))
-            then
-                check "$tfile" \
-                      "One or more files has formatting errors. Please review. $remediation"
-            else
-                ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl perltidy, no perl perltidy helpers found."
+                ((runcheck==1)) && check "$tfile" \
+                                         "One or more files has syntax errors. Please review."
             fi
+
+            ##
+            ## check: repo tidy tests
+            ##
+            if [ -n "${skips[perltidy]}" ]
+            then
+                ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl perltidy check, by request."
+            else
+                declare remediation
+                declare tidycmd
+                declare runcheck=0
+                for tidycmd in \
+                    "$gitroot/t/bin/apply-perltidy-everywhere" \
+                        "${TILDAE:-$HOME}/personal/bin/apply-perltidy-everywhere"
+                do
+                    if [ -e "$tidycmd" ]
+                    then
+                        "$tidycmd" "${perlfiles[@]}" 1>"$tfile" 2>&1
+                        runcheck=1
+                        remediation="To correct, run $tidycmd --update ${perlfiles[*]}"
+                        break
+                    fi
+                done
+                if ((runcheck==1))
+                then
+                    check "$tfile" \
+                          "One or more files has formatting errors. Please review. $remediation"
+                else
+                    ((opt_verbose)) && pre_commit_ok_echo "Skipping Perl perltidy, no perl perltidy helpers found."
+                fi
+            fi
+        else
+            echo "Skipping perl checks, by request."
         fi
     fi
 
@@ -414,6 +405,7 @@ then
             echo "Skipping python black, by request."
         fi
     fi
+
     ##
     ## check; git conflict markers
     ##
@@ -438,11 +430,18 @@ fi
 ##
 ## Done
 ##
+
 if ((exitval==0))
 then
-    pre_commit_ok_echo "Ok to commit"
+    if((opt_nocommit))
+    then
+        pre_commit_ok_echo 'No errors, but --nocommit specified. Commit will be aborted.'
+        exitval=1
+    else
+        pre_commit_ok_echo 'Commit will proceed.'
+    fi
 else
-    pre_commit_error_echo "Commit will abort"
+    pre_commit_error_echo 'Commit will abort.'
 fi
 exit $exitval
 
@@ -453,8 +452,7 @@ pre-commit - a script for the pre-commit hook in git
 
 =head1 SYNOPSIS
 
-   pre-commit [-a] [--quiet] [--help] [--skip ... [ --skip ... ] ]
-
+   pre-commit [--nocommit] [--quiet] [--skip ... [ --skip ... ] ]
    pre-commit --help
 
 =head1 DESCRIPTION
@@ -533,8 +531,8 @@ We don't let you commit code with conflict markers.
 None
 
 <soapbox> You'd think that git would pass us the files it's about to commit,
-but no; we have to run 'git status --porcelain' and parse the output determine
-what files are about to be committed. </soapbox>
+but no; we have to run 'git diff-index --porcelain HEAD' and parse the output
+determine what files are about to be committed. </soapbox>
 
 =over 4
 
@@ -548,19 +546,13 @@ git command:
 
     GIT_PRE_COMMIT_HOOK_ARGS="--quiet --skip perltidy" git commit ...
 
-Note that we filter out '--help' and '-a' if you specify them; they do not
-apply when using the hook in a real commit. They are only provided for use when
-you are running the hook itself as a script.
+Note that we filter out '--help' if you specify it; they do not apply when
+using the hook in a real commit. They are only provided for use when you are
+running the hook itself as a script.
 
-=over 4
+=item --nocommit
 
-=item -a
-
-Mimic the '-a' of 'git commit' and process all files that are modified, staged
-or not. This is only needed for test mode; in live mode, if you pass '-a' to 'git
-commit', by the time the hook is invoked, even the non-staged files appear to be
-staged. Do NOT use this on a real commit; let the commit command Do The Right
-Thing.
+Does everything except the commit. Used for testing the hook.
 
 =item --quiet
 
@@ -573,8 +565,10 @@ Skip one or more validations:
   perlcompile
   perltidy
   perl (both compile and tidy)
+
   shellcheck
   shell (short for shellcheck)
+
   python (black format check)
   py (short for python)
 
